# Generated by Django 3.0.4 on 2020-05-30 16:58

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblogpage',
            name='contents',
            field=wagtail.core.fields.StreamField([('title', streams.blocks.TitleBlock()), ('paragraph', streams.blocks.ParaBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(classname='post_image', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('date', streams.blocks.DmyBlock())], blank=True, null=True, verbose_name='My Stream'),
        ),
    ]
