# Generated by Django 3.0.4 on 2020-05-30 17:26

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0003_auto_20200530_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('contents', wagtail.core.fields.StreamField([('title', streams.blocks.TitleBlock()), ('paragraph', streams.blocks.ParaBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(classname='post_image', required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('date', streams.blocks.DmyBlock())], blank=True, null=True, verbose_name='My Stream')),
            ],
            options={
                'verbose_name': 'New blog page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='contents',
        ),
    ]
