# Generated by Django 3.0.4 on 2020-07-26 15:02

import blog.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("blog", "0006_auto_20200726_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamTextPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("body", wagtail.core.fields.RichTextField(blank=True)),
                (
                    "contents",
                    wagtail.core.fields.StreamField(
                        [
                            ("paragraph", blog.blocks.ParaBlock()),
                            (
                                "code",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "language",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("bash", "Bash/Shell"),
                                                    ("css", "CSS"),
                                                    ("diff", "diff"),
                                                    ("html", "HTML"),
                                                    ("javascript", "Javascript"),
                                                    ("json", "JSON"),
                                                    ("python", "Python"),
                                                    ("scss", "SCSS"),
                                                    ("yaml", "YAML"),
                                                ],
                                                help_text="Coding language",
                                                identifier="language",
                                                label="Language",
                                            ),
                                        ),
                                        (
                                            "code",
                                            wagtail.core.blocks.TextBlock(
                                                identifier="code", label="Code"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("html", blog.blocks.HTMLBlock()),
                        ],
                        blank=True,
                        null=True,
                        verbose_name="My Stream",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
