# Generated by Django 3.0.4 on 2020-06-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200607_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamblogpage',
            options={'verbose_name': 'Stream blog page'},
        ),
    ]
