# Generated by Django 3.1 on 2020-08-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailcore", "0052_pagelogentry"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("blog", "0007_streamtextpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogTagIndexPage",
        ),
    ]
