# Generated by Django 3.1 on 2020-08-20 08:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
        ("blog", "0008_delete_blogtagindexpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTagIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                "wagtailcore.page",
                wagtail.contrib.routable_page.models.RoutablePageMixin,
            ),
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(max_length=80, null=True, unique=True),
        ),
    ]
