# Generated by Django 3.0.4 on 2020-06-09 18:59

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200607_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamblogpage',
            name='contents',
            field=wagtail.core.fields.StreamField([('paragraph', blog.blocks.ParaBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(classname='post_image', required=False, template='blog/streams/pic_block.html')), ('caption', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True, verbose_name='My Stream'),
        ),
    ]
