# Generated by Django 3.1 on 2020-08-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20200820_1048"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name": "Categories"},
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="icon",
        ),
    ]
