# Generated by Django 3.1 on 2020-11-14 15:37

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20200820_1347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamblogpage",
            name="contents",
            field=wagtail.core.fields.StreamField(
                [
                    ("paragraph", blog.blocks.ParaBlock()),
                    (
                        "code",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bash", "Bash/Shell"),
                                            ("css", "CSS"),
                                            ("diff", "diff"),
                                            ("html", "HTML"),
                                            ("javascript", "Javascript"),
                                            ("json", "JSON"),
                                            ("python", "Python"),
                                            ("scss", "SCSS"),
                                            ("yaml", "YAML"),
                                        ],
                                        help_text="Coding language",
                                        identifier="language",
                                        label="Language",
                                    ),
                                ),
                                (
                                    "code",
                                    wagtail.core.blocks.TextBlock(
                                        identifier="code", label="Code"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("html", blog.blocks.HTMLBlock()),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Caption", required=False
                                    ),
                                ),
                                (
                                    "float",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("right", "Right"),
                                            ("left", "Left"),
                                            ("center", "Center"),
                                        ],
                                        label="Float",
                                        required=False,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "Small"),
                                            ("medium", "Medium"),
                                            ("large", "Large"),
                                        ],
                                        label="Size",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                verbose_name="My Stream",
            ),
        ),
        migrations.AlterField(
            model_name="streamtextpage",
            name="contents",
            field=wagtail.core.fields.StreamField(
                [
                    ("paragraph", blog.blocks.ParaBlock()),
                    (
                        "code",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bash", "Bash/Shell"),
                                            ("css", "CSS"),
                                            ("diff", "diff"),
                                            ("html", "HTML"),
                                            ("javascript", "Javascript"),
                                            ("json", "JSON"),
                                            ("python", "Python"),
                                            ("scss", "SCSS"),
                                            ("yaml", "YAML"),
                                        ],
                                        help_text="Coding language",
                                        identifier="language",
                                        label="Language",
                                    ),
                                ),
                                (
                                    "code",
                                    wagtail.core.blocks.TextBlock(
                                        identifier="code", label="Code"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("html", blog.blocks.HTMLBlock()),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Caption", required=False
                                    ),
                                ),
                                (
                                    "float",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("right", "Right"),
                                            ("left", "Left"),
                                            ("center", "Center"),
                                        ],
                                        label="Float",
                                        required=False,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("small", "Small"),
                                            ("medium", "Medium"),
                                            ("large", "Large"),
                                        ],
                                        label="Size",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                verbose_name="My Stream",
            ),
        ),
    ]
