# Generated by Django 3.1.12 on 2021-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_add_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='last_modified',
            field=models.DateField(verbose_name='Last updated'),
        ),
    ]
